### ISSUE TITLE
There is no command for "imgmake"

### ISSUE THREAD

**Issue by SamParisot** [SparrOSDeveloperTeam/Windows-95-Dreamcast#1]

**Comment by SparrOSDeveloperTeam** [comment]
Ah yes. IMGMAKE. I guess I should have mentioned it's for DOSBOX Daum builds. Use bximage to create the img.

**Comment by SamParisot** [comment]
Ah. K. Thank you. I already have DOSBox Daum installed so thats not a big problem.
Case closed.

**Comment by SparrOSDeveloperTeam** [comment]
Glad I can help :) If you were wondering where you can get a copy of bximage.exe, just download the Bochs-Tools pack in the wiki.
